# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Preparing Sonarcloud'
  inputs:
    SonarCloud: 'markToken'
    organization: 'markpipelinedemorepo'
    scannerMode: 'MSBuild'
    projectKey: 'markPipelineDemoRepo_markPipelineDemoRepoProject'
    projectName: 'markPipelineDemoRepoProject'
    extraProperties: |
      sonar.exclusions=**/lib/**

- script: dotnet build ./12142020_MvcRpsDemo/12142020_MvcRpsDemo.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Building Tests'
  inputs:
    command: 'test'
    projects: './12142020_MvcRpsDemo/12142020_MvcRpsDemo.Tests/12142020_MvcRpsDemo.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'

- task: PublishCodeCoverageResults@1
  displayName: 'publish code coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coburtura/coverage.xml'
- task: SonarCloudAnalyze@1
  displayName: 'SONARCLOUD Analyze'

- task: SonarCloudPublish@1
  displayName: 'Sonarcloud Publishing'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'app publish and zip'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(5d150957-9944-40b9-b9e9-2a32c983a1f8)'
    appType: 'webApp'
    WebAppName: 'MarkPipelineDemo12142020'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'











