# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Preparing Sonarcloud'
  inputs:
    SonarCloud: 'markToken'
    organization: 'markpipelinedemorepo'
    scannerMode: 'MSBuild'
    projectKey: 'markPipelineDemoRepo_markPipelineDemoRepoProject'
    projectName: 'markPipelineDemoRepoProject'

- script: dotnet build ./12142020_MvcRpsDemo --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'SONARCLOUD Analyze'

- task: SonarCloudPublish@1
  displayName: 'Sonarcloud Publishing'
  inputs:
    pollingTimeoutSec: '300'